import type { RewindCardTheme } from "./media.rewind.types";

export const MUSIC_VARIANTS: RewindCardTheme[] = [
  {
    container:
      "rounded-2xl shadow-[0_20px_50px_-15px_rgba(0,0,0,0.8)] bg-[#0a0a0a] border-none",
    title:
      "text-[#ccff00] font-black uppercase tracking-tighter text-2xl md:text-4xl mix-blend-difference drop-shadow-lg",
    text: "text-white font-black uppercase tracking-tight",
    highlight: "text-black bg-[#ccff00] px-3 py-1 rotate-1 inline-block",
    pattern: { kind: "checkerboard", color: "#ffffff", opacity: 0.2 },
    decoration: "asterisk-burst",
    scrollFade: "from-black/40",
  },
  {
    container: "rounded-3xl shadow-2xl bg-[#4338ca] border-none",
    title:
      "text-[#fb923c] font-black uppercase text-lg md:text-2xl tracking-widest px-6 py-2 bg-[#312e81] inline-block rounded-full shadow-xl",
    text: "text-indigo-50 font-bold",
    highlight: "text-[#fb923c]",
    pattern: { kind: "concentric-rings", color: "#3730a3", colorAlt: "#312e81", opacity: 0.5 },
    decoration: "orbit-ring",
    scrollFade: "from-[#4338ca]",
  },
  {
    container: "rounded-none border-[12px] border-black shadow-[8px_8px_0_0_#000] bg-[#f4f4f5]",
    title:
      "text-black font-black uppercase text-xl md:text-3xl bg-white inline-block px-4 py-2 border-4 border-black",
    text: "text-black font-black uppercase tracking-tight",
    highlight: "text-white bg-black px-4 py-1 inline-block -rotate-2",
    pattern: { kind: "polka-dots", color: "#000000", opacity: 0.1 },
    decoration: "corner-brackets",
    scrollFade: "from-[#f4f4f5]",
  },
  {
    container: "rounded-sm border-8 border-neutral-800 shadow-2xl bg-[#0c0c0c]",
    title: "text-[#ef4444] font-black uppercase tracking-[0.35em] text-lg md:text-2xl",
    text: "text-neutral-200 font-medium tracking-wide",
    highlight: "text-white bg-[#ef4444] px-2 py-0.5 inline-block",
    pattern: { kind: "vinyl-grooves", color: "#ffffff", opacity: 0.22 },
    decoration: "stamp-seal",
    scrollFade: "from-black/50",
  },
  {
    container:
      "rounded-none border-none shadow-[0_0_40px_rgba(219,39,116,0.45)] bg-gradient-to-b from-[#2e1065] via-[#db2777] to-[#f97316]",
    title: "text-white font-black uppercase italic text-2xl md:text-4xl drop-shadow-[0_0_12px_#f0abfc]",
    text: "text-fuchsia-50 font-bold tracking-wide",
    highlight: "text-[#2e1065] bg-cyan-300 px-2 py-0.5 inline-block",
    pattern: { kind: "hex-grid", color: "#22d3ee", opacity: 0.35 },
    decoration: "neon-frame",
    scrollFade: "from-[#f97316]",
  },
  {
    container: "rounded-xl border-4 border-[#facc15] shadow-[6px_6px_0_0_#facc15] bg-[#f43f5e]",
    title: "text-[#facc15] font-black uppercase text-xl md:text-3xl -rotate-1",
    text: "text-white font-black uppercase",
    highlight: "text-[#f43f5e] bg-[#facc15] px-2 py-1 inline-block rotate-2",
    pattern: { kind: "speed-lines", color: "#fde047", opacity: 0.35 },
    decoration: "washi-tape",
    scrollFade: "from-[#f43f5e]",
  },
  {
    container: "rounded-md border-y-[14px] border-x-[6px] border-[#78350f] shadow-lg bg-[#fef3c7]",
    title: "text-[#78350f] font-mono font-bold uppercase tracking-widest text-sm md:text-xl",
    text: "text-[#1c1917] font-mono",
    highlight: "text-[#fef3c7] bg-[#b45309] px-1.5 py-0.5",
    pattern: { kind: "waveform", color: "#b45309", opacity: 0.45 },
    decoration: "play-glyph",
    scrollFade: "from-[#fef3c7]",
  },
  {
    container: "rounded-2xl border border-white/10 shadow-2xl bg-[#111827]",
    title: "text-red-400 font-mono uppercase tracking-[0.4em] text-sm md:text-lg",
    text: "text-zinc-300 font-light",
    highlight: "text-red-300 underline decoration-red-500/80",
    pattern: { kind: "scanlines", color: "#f87171", opacity: 0.18 },
    decoration: "rec-badge",
    scrollFade: "from-[#111827]",
  },
  {
    container:
      "rounded-2xl border border-white/40 shadow-[inset_0_1px_0_rgba(255,255,255,0.6),0_18px_40px_rgba(0,0,0,0.35)] bg-gradient-to-br from-[#e5e5e5] via-[#a3a3a3] to-[#525252]",
    title: "text-black font-black uppercase italic text-2xl md:text-4xl",
    text: "text-neutral-900 font-semibold",
    highlight: "text-white bg-black px-2 py-0.5 inline-block",
    pattern: { kind: "diagonal-stripes", color: "#ffffff", opacity: 0.28 },
    decoration: "timestamp-osd",
    scrollFade: "from-[#525252]",
  },
  {
    container: "rounded-none border-x-[10px] border-y-0 border-[#f97316] shadow-xl bg-[#facc15]",
    title: "text-black font-black uppercase tracking-tighter text-2xl md:text-4xl",
    text: "text-black font-bold",
    highlight: "text-[#facc15] bg-black px-2 py-1 inline-block",
    pattern: { kind: "ticket-stub", color: "var(--bg-0)", opacity: 1 },
    decoration: "laurel",
    scrollFade: "from-[#facc15]",
  },
  {
    container: "rounded-3xl border-2 border-cyan-400/60 shadow-[0_0_28px_rgba(34,211,238,0.35)] bg-[#083344]",
    title: "text-cyan-300 font-mono font-bold uppercase tracking-[0.25em] text-lg md:text-2xl",
    text: "text-cyan-50 font-mono",
    highlight: "text-[#083344] bg-cyan-300 px-2 py-0.5",
    pattern: { kind: "paper-noise", color: "#67e8f9", opacity: 0.25 },
    decoration: "vignette",
    scrollFade: "from-[#083344]",
  },
  {
    container: "rounded-2xl border-2 border-[#ff00ff] shadow-[0_0_30px_#ff00ff] bg-[#1a001a]",
    title: "text-[#00ffff] font-black uppercase text-xl md:text-3xl drop-shadow-[0_0_8px_#00ffff]",
    text: "text-pink-100 font-bold",
    highlight: "text-black bg-[#00ffff] px-2 py-0.5 inline-block -rotate-1",
    pattern: { kind: "halftone", color: "#ff00ff", opacity: 0.4 },
    decoration: "quote-marks",
    scrollFade: "from-[#1a001a]",
  },
];

export const WATCH_VARIANTS: RewindCardTheme[] = [
  {
    container: "rounded-2xl shadow-[0_20px_50px_-15px_rgba(0,0,0,0.8)] bg-black border border-neutral-800",
    title: "text-[#fcd34d] font-serif italic text-2xl md:text-4xl opacity-80",
    text: "text-neutral-300 font-light tracking-wide",
    highlight: "text-white font-normal",
    pattern: { kind: "film-bars", color: "#171717", opacity: 1 },
    decoration: "vignette",
    scrollFade: "from-black/50",
  },
  {
    container: "rounded-sm border-8 border-[#fbbf24] shadow-xl bg-[#1e3a8a]",
    title:
      "text-[#fbbf24] font-black uppercase text-lg md:text-2xl tracking-[0.3em] border-y-4 border-[#fbbf24] py-3 inline-block",
    text: "text-blue-50 font-bold uppercase",
    highlight: "text-[#1e3a8a] bg-[#fbbf24] px-3 py-1",
    pattern: { kind: "ticket-stub", color: "var(--bg-0)", opacity: 1 },
    decoration: "stamp-seal",
    scrollFade: "from-[#1e3a8a]",
  },
  {
    container: "rounded-md border-2 border-cyan-900 shadow-[0_0_24px_rgba(34,211,238,0.2)] bg-[#0f172a]",
    title:
      "text-cyan-400 font-mono font-bold uppercase text-xl md:text-3xl tracking-widest bg-[#0f172a] inline-block px-4 py-2 border border-cyan-800",
    text: "text-slate-300 font-mono",
    highlight: "text-cyan-200 bg-cyan-900/80 px-2 py-1 border border-cyan-400/50",
    pattern: { kind: "scanlines", color: "#22d3ee", opacity: 0.22 },
    decoration: "rec-badge",
    scrollFade: "from-[#0f172a]",
  },
  {
    container: "rounded-none border-[10px] border-black shadow-2xl bg-[#7f1d1d]",
    title: "text-white font-black uppercase tracking-[0.4em] text-lg md:text-2xl",
    text: "text-red-50 font-semibold tracking-wide",
    highlight: "text-[#7f1d1d] bg-white px-2 py-0.5 inline-block",
    pattern: { kind: "hex-grid", color: "#fecaca", opacity: 0.2 },
    decoration: "neon-frame",
    scrollFade: "from-[#7f1d1d]",
  },
  {
    container: "rounded-none border-4 border-[#14532d] shadow-inner bg-[#14532d]",
    title: "text-[#86efac] font-mono uppercase tracking-[0.2em] text-sm md:text-xl",
    text: "text-green-100 font-mono",
    highlight: "text-black bg-[#86efac] px-1.5",
    pattern: { kind: "paper-noise", color: "#bbf7d0", opacity: 0.3 },
    decoration: "timestamp-osd",
    scrollFade: "from-[#14532d]",
  },
  {
    container: "rounded-2xl border-4 border-amber-300 shadow-[0_0_20px_rgba(252,211,77,0.35)] bg-[#111827]",
    title: "text-amber-200 font-serif italic text-2xl md:text-4xl",
    text: "text-amber-50 font-light tracking-widest uppercase",
    highlight: "text-[#111827] bg-amber-300 px-2 py-0.5",
    pattern: { kind: "polka-dots", color: "#fcd34d", opacity: 0.28 },
    decoration: "asterisk-burst",
    scrollFade: "from-[#111827]",
  },
  {
    container: "rounded-none border border-neutral-400 shadow-md bg-[#e7e5e4]",
    title: "text-neutral-800 font-sans font-bold uppercase tracking-widest text-sm md:text-lg border-b border-neutral-500 pb-2",
    text: "text-neutral-700 font-sans leading-relaxed",
    highlight: "text-black bg-yellow-200 px-1",
    pattern: { kind: "margin-line", color: "#a8a29e", opacity: 0.5 },
    decoration: "corner-brackets",
    scrollFade: "from-[#e7e5e4]",
  },
  {
    container: "rounded-sm border-[6px] border-neutral-900 shadow-xl bg-[#1c1917]",
    title: "text-white font-black uppercase text-xl md:text-3xl",
    text: "text-stone-200 font-medium",
    highlight: "text-black bg-white px-2 py-0.5 inline-block",
    pattern: { kind: "checkerboard", color: "#ffffff", opacity: 0.18 },
    decoration: "play-glyph",
    scrollFade: "from-[#1c1917]",
  },
  {
    container: "rounded-none border-[14px] border-white shadow-2xl bg-[#0a0a0a]",
    title: "text-white font-serif italic text-2xl md:text-4xl",
    text: "text-neutral-300 font-serif font-light leading-relaxed",
    highlight: "text-white border-b border-white/70",
    pattern: { kind: "concentric-rings", color: "#404040", colorAlt: "#262626", opacity: 0.45 },
    decoration: "quote-marks",
    scrollFade: "from-black/60",
  },
  {
    container:
      "rounded-3xl border-none shadow-[0_20px_50px_-15px_rgba(0,0,0,0.8)] bg-gradient-to-b from-[#2e1065] to-[#0c0a09]",
    title: "text-orange-200 font-serif italic text-2xl md:text-4xl",
    text: "text-purple-100 font-light tracking-wide",
    highlight: "text-orange-200",
    pattern: { kind: "speed-lines", color: "#fdba74", opacity: 0.2 },
    decoration: "orbit-ring",
    scrollFade: "from-[#0c0a09]",
  },
  {
    container: "rounded-none border-x-[18px] border-y-0 border-neutral-900 shadow-2xl bg-[#171717]",
    title: "text-neutral-100 font-black uppercase tracking-[0.15em] text-lg md:text-2xl",
    text: "text-neutral-300 font-medium",
    highlight: "text-black bg-neutral-100 px-2 py-0.5",
    pattern: { kind: "vinyl-grooves", color: "#d4d4d4", opacity: 0.2 },
    decoration: "washi-tape",
    scrollFade: "from-[#171717]",
  },
  {
    container: "rounded-xl border-4 border-[#fbbf24] shadow-[0_0_28px_rgba(251,191,36,0.35)] bg-[#78350f]",
    title: "text-[#fde68a] font-serif uppercase tracking-[0.25em] text-lg md:text-2xl",
    text: "text-amber-50 font-serif",
    highlight: "text-[#78350f] bg-[#fde68a] px-2 py-0.5",
    pattern: { kind: "halftone", color: "#fcd34d", opacity: 0.3 },
    decoration: "laurel",
    scrollFade: "from-[#78350f]",
  },
];

export const READ_VARIANTS: RewindCardTheme[] = [
  {
    container: "rounded-2xl shadow-lg bg-[#fef3c7] border border-[#d4d4d8]",
    title:
      "text-[#991b1b] font-serif uppercase tracking-widest text-xl md:text-3xl border-b-2 border-[#991b1b] pb-2 inline-block",
    text: "text-[#1c1917] font-serif leading-relaxed",
    highlight: "text-[#991b1b] font-bold italic",
    pattern: { kind: "paper-noise", color: "#000000", opacity: 0.35 },
    decoration: "margin-line",
    scrollFade: "from-[#fef3c7]",
  },
  {
    container: "rounded-none border-[16px] border-black shadow-[10px_10px_0_0_#000] bg-white",
    title:
      "text-black font-sans font-black uppercase text-2xl md:text-4xl bg-white inline-block pr-4 relative z-10",
    text: "text-black font-sans font-medium relative z-10",
    highlight: "text-white bg-red-600 px-3 py-1 inline-block",
    pattern: { kind: "margin-line", color: "#000000", opacity: 0.2 },
    decoration: "corner-brackets",
    scrollFade: "from-white",
  },
  {
    container: "rounded-2xl border-none shadow-2xl bg-[#064e3b]",
    title: "text-emerald-200 font-serif italic text-2xl md:text-4xl relative z-10",
    text: "text-emerald-50 font-serif font-light relative z-10",
    highlight: "text-emerald-200 border-b-2 border-emerald-400",
    pattern: { kind: "diagonal-stripes", color: "#ffffff", opacity: 0.2 },
    decoration: "orbit-ring",
    scrollFade: "from-[#064e3b]",
  },
  {
    container: "rounded-sm border border-[#b45309] shadow-md bg-[#f4f1de]",
    title: "text-[#7c2d12] font-mono uppercase tracking-[0.2em] text-sm md:text-lg",
    text: "text-[#44403c] font-sans leading-relaxed",
    highlight: "text-[#7c2d12] font-bold underline decoration-[#b45309]",
    pattern: { kind: "checkerboard", color: "#b45309", opacity: 0.12 },
    decoration: "binder-holes",
    scrollFade: "from-[#f4f1de]",
  },
  {
    container: "rounded-xl border border-indigo-900 shadow-xl bg-[#1e3a5f]",
    title: "text-[#fde68a] font-serif italic text-2xl md:text-4xl",
    text: "text-indigo-50 font-serif leading-relaxed",
    highlight: "text-[#1e3a5f] bg-[#fde68a] px-1.5 italic",
    pattern: { kind: "concentric-rings", color: "#312e81", colorAlt: "#1e3a8a", opacity: 0.45 },
    decoration: "quote-marks",
    scrollFade: "from-[#1e3a5f]",
  },
  {
    container: "rounded-md border-[10px] border-[#9a3412] shadow-lg bg-[#fff7ed]",
    title: "text-[#9a3412] font-black uppercase tracking-tight text-xl md:text-3xl",
    text: "text-[#431407] font-serif",
    highlight: "text-white bg-[#c2410c] px-2 py-0.5 inline-block",
    pattern: { kind: "polka-dots", color: "#9a3412", opacity: 0.12 },
    decoration: "washi-tape",
    scrollFade: "from-[#fff7ed]",
  },
  {
    container: "rounded-3xl border border-violet-200 shadow-lg bg-[#faf5ff]",
    title: "text-violet-900 font-serif italic text-2xl md:text-4xl",
    text: "text-violet-950 font-serif font-light leading-loose",
    highlight: "text-violet-800 italic",
    pattern: { kind: "hex-grid", color: "#c4b5fd", opacity: 0.45 },
    decoration: "asterisk-burst",
    scrollFade: "from-[#faf5ff]",
  },
  {
    container: "rounded-lg border-2 border-yellow-300 shadow-md bg-[#fefce8]",
    title: "text-neutral-800 font-sans font-bold uppercase tracking-wide text-lg md:text-2xl",
    text: "text-neutral-700 font-sans leading-relaxed",
    highlight: "bg-yellow-300 text-neutral-900 px-1",
    pattern: { kind: "halftone", color: "#ca8a04", opacity: 0.25 },
    decoration: "neon-frame",
    scrollFade: "from-[#fefce8]",
  },
  {
    container: "rounded-2xl border-[6px] border-[#9f1239] shadow-xl bg-[#fff1f2]",
    title: "text-[#9f1239] font-serif uppercase tracking-[0.3em] text-sm md:text-xl",
    text: "text-rose-950 font-serif leading-relaxed",
    highlight: "text-[#9f1239] font-bold",
    pattern: { kind: "vinyl-grooves", color: "#9f1239", opacity: 0.18 },
    decoration: "stamp-seal",
    scrollFade: "from-[#fff1f2]",
  },
  {
    container: "rounded-none border border-neutral-400 shadow-sm bg-[#f5f5f4]",
    title: "text-neutral-800 font-mono uppercase tracking-[0.15em] text-sm md:text-lg",
    text: "text-neutral-700 font-mono leading-relaxed",
    highlight: "text-black underline decoration-2",
    pattern: { kind: "scanlines", color: "#a8a29e", opacity: 0.45 },
    decoration: "play-glyph",
    scrollFade: "from-[#f5f5f4]",
  },
  {
    container: "rounded-sm border-2 border-[#fbbf24] shadow-[0_0_24px_rgba(251,191,36,0.25)] bg-[#111827]",
    title: "text-[#fbbf24] font-serif uppercase tracking-[0.35em] text-lg md:text-2xl",
    text: "text-amber-50 font-serif leading-relaxed",
    highlight: "text-[#fbbf24] italic",
    pattern: { kind: "speed-lines", color: "#fbbf24", opacity: 0.18 },
    decoration: "laurel",
    scrollFade: "from-[#111827]",
  },
  {
    container: "rounded-2xl border border-[#a8a29e] shadow-inner bg-[#d6bfa3]",
    title: "text-[#44403c] font-serif italic text-2xl md:text-4xl",
    text: "text-[#1c1917] font-serif leading-relaxed",
    highlight: "text-[#7c2d12] font-semibold italic",
    pattern: { kind: "film-bars", color: "#a8a29e", opacity: 0.8 },
    decoration: "vignette",
    scrollFade: "from-[#d6bfa3]",
  },
];
